"""
doc_builder.py — Professional Word document builder for IBM documentation.

FIXES:
  P1 — Backtick code fences now rendered as shaded Courier blocks, not raw text.
  P2 — Trivial filler docs handled gracefully (threshold raised in compressor.py).
  P3 — Inline docstring extracted from code fence, rendered as shaded block.
  P4 — Sections no longer cut off (max_tokens raised in config/github_client).
  P5 — Architecture diagram: try/except + text fallback table if image missing.
  P6 — Project summary passed through _add_markdown() — no raw ### or ** in Word.
  P7 — Page border via sectPr XML. Body text justified. Table borders explicit XML.
"""

import re
import time
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from lxml import etree


# ─────────────────────────────────────────────────────────────────────────────
#  Document creation
# ─────────────────────────────────────────────────────────────────────────────

def create_doc(project_name: str = "Project") -> Document:
    doc = Document()

    # Set narrow margins for more content per page
    for section in doc.sections:
        section.top_margin    = Inches(0.9)
        section.bottom_margin = Inches(0.9)
        section.left_margin   = Inches(1.0)
        section.right_margin  = Inches(1.0)

    # Title page
    title = doc.add_heading(f"AI Code Documentation — {project_name}", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph(
        "Generated by AI-powered multi-model pipeline "
        "(Groq → GPT-4o → gpt-4o-mini + Phi-4)"
    )
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].italic = True

    doc.add_page_break()

    # P7: Add page border to document
    _add_page_border(doc)

    return doc


def _add_page_border(doc: Document):
    """P7: Add a thin single-line border around every page via sectPr XML."""
    for section in doc.sections:
        sectPr = section._sectPr
        pgBorders = OxmlElement("w:pgBorders")
        pgBorders.set(qn("w:offsetFrom"), "page")
        for side in ("top", "left", "bottom", "right"):
            border = OxmlElement(f"w:{side}")
            border.set(qn("w:val"),   "single")
            border.set(qn("w:sz"),    "6")       # 0.75pt
            border.set(qn("w:space"), "24")
            border.set(qn("w:color"), "4A4A6A")
            pgBorders.append(border)
        sectPr.append(pgBorders)


# ─────────────────────────────────────────────────────────────────────────────
#  Section headings
# ─────────────────────────────────────────────────────────────────────────────

def add_file_heading(doc: Document, filename: str, lang: str):
    doc.add_heading(f"📄 {filename}", level=1)
    p = doc.add_paragraph()
    r = p.add_run(f"Language: {lang.upper()}")
    r.italic = True
    r.font.color.rgb = RGBColor(0x60, 0x60, 0x90)


def add_unit_doc(doc: Document, name: str, unit_type: str,
                 documentation: str, score: float = 0):
    icon  = "🔧" if unit_type == "function" else "🏛️"
    h     = doc.add_heading(f"{icon} {name}", level=2)
    h.alignment = WD_ALIGN_PARAGRAPH.LEFT

    # Quality badge
    stars = "⭐" * round(score)
    badge = doc.add_paragraph()
    run   = badge.add_run(f"Quality: {stars} {score:.1f}/5")
    run.italic = True
    run.font.color.rgb = RGBColor(0x55, 0x55, 0x88)

    doc.add_paragraph("─" * 60).runs[0].font.color.rgb = RGBColor(0x44, 0x44, 0x66)

    # P1/P3/P6: documentation goes through full markdown renderer
    _add_markdown(doc, documentation)

    doc.add_paragraph()   # breathing room between functions


# ─────────────────────────────────────────────────────────────────────────────
#  Markdown renderer — fixes P1, P3, P6
# ─────────────────────────────────────────────────────────────────────────────

def _add_markdown(doc: Document, text: str):
    """
    Convert markdown-formatted text to proper Word paragraphs.

    Handles:
      ``` code fences ```  → shaded Courier New block        (fixes P1, P3)
      ### ## # headings    → Word heading levels
      **bold** *italic*    → formatted runs
      - bullet             → List Bullet style
      1. numbered          → List Number style
      | table | rows |     → Word table
      ---                  → horizontal rule (thin paragraph border)
      blank lines          → small spacer paragraph
    """
    lines      = text.splitlines()
    i          = 0
    in_fence   = False
    fence_lang = "python"
    fence_buf  : list = []

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # ── Code fence handling ────────────────────────────────────────────
        if stripped.startswith("```"):
            if not in_fence:
                # Opening fence
                in_fence   = True
                fence_lang = stripped[3:].strip() or "python"
                fence_buf  = []
            else:
                # Closing fence — render buffered code as shaded block
                in_fence = False
                _add_code_block(doc, "\n".join(fence_buf), fence_lang)
                fence_buf = []
            i += 1
            continue

        if in_fence:
            fence_buf.append(line)
            i += 1
            continue

        # ── Headings ──────────────────────────────────────────────────────
        if stripped.startswith("### "):
            h = doc.add_heading(_strip_inline_md(stripped[4:]), level=3)
            h.alignment = WD_ALIGN_PARAGRAPH.LEFT
            i += 1
            continue
        if stripped.startswith("## "):
            h = doc.add_heading(_strip_inline_md(stripped[3:]), level=2)
            h.alignment = WD_ALIGN_PARAGRAPH.LEFT
            i += 1
            continue
        if stripped.startswith("# "):
            h = doc.add_heading(_strip_inline_md(stripped[2:]), level=1)
            h.alignment = WD_ALIGN_PARAGRAPH.LEFT
            i += 1
            continue

        # ── Horizontal rule ────────────────────────────────────────────────
        if stripped in ("---", "***", "___"):
            p = doc.add_paragraph()
            _add_bottom_border(p)
            i += 1
            continue

        # ── Bullet list ────────────────────────────────────────────────────
        if stripped.startswith("- ") or stripped.startswith("* "):
            p = _add_inline(doc, stripped[2:])
            p.style = doc.styles["List Bullet"]
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            i += 1
            continue

        # ── Numbered list ──────────────────────────────────────────────────
        # FIX: plain paragraph not List Number style — List Number auto-increments
        # across the entire document causing steps to run 1–43 instead of per-function
        num_match = re.match(r'^(\d+)\.\s+(.*)', stripped)
        if num_match:
            p = _add_inline(doc, f"{num_match.group(1)}. {num_match.group(2)}")
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            p.paragraph_format.left_indent = Pt(18)
            i += 1
            continue

        # ── Table rows ─────────────────────────────────────────────────────
        if stripped.startswith("|") and stripped.endswith("|"):
            # Collect all consecutive table rows
            table_lines = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                table_lines.append(lines[i].strip())
                i += 1
            _add_table(doc, table_lines)
            continue

        # ── Blank line → small spacer ──────────────────────────────────────
        if not stripped:
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(2)
            i += 1
            continue

        # ── Regular paragraph ──────────────────────────────────────────────
        # FIX: clean up GPT-4o backtick artifacts in Returns/Cross-Ref lines
        clean = stripped
        # "class` — desc" or "function` — desc"
        clean = re.sub(r'^(class|function)\s*`\s*', '', clean)
        # "name` — desc" → "name — desc"
        clean = re.sub(r'(\w)`(\s*\u2014|\s*-)', lambda m: m.group(1) + m.group(2), clean)
        clean = re.sub(r'(\w)`(\s*—)', r'\1\2', clean)
        # ": If the keyboard..." → "If the keyboard..." (dangling colon)
        clean = re.sub(r'^:\s+', '', clean)
        p = _add_inline(doc, clean)
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY   # P7: justify all body text
        i += 1


def _add_code_block(doc: Document, code: str, language: str = "python"):
    """
    Render a code block as a shaded Courier New paragraph.
    P1: backtick fences → proper Word code block (not raw text).
    P3: docstring content extracted and rendered here, not as backtick text.
    """
    # Strip leading/trailing blank lines
    code_lines = code.strip().splitlines()
    if not code_lines:
        return

    for line in code_lines:
        p = doc.add_paragraph()
        p.style = doc.styles["Normal"]
        p.paragraph_format.space_before = Pt(0)
        p.paragraph_format.space_after  = Pt(0)
        p.paragraph_format.left_indent  = Inches(0.3)

        # Grey shading on paragraph
        pPr  = p._p.get_or_add_pPr()
        shd  = OxmlElement("w:shd")
        shd.set(qn("w:val"),   "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"),  "F0F0F4")
        pPr.append(shd)

        run = p.add_run(line if line else " ")
        run.font.name = "Courier New"
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x4A)


def _add_inline(doc: Document, text: str):
    """Parse inline markdown (bold, italic, inline code) into a Word paragraph."""
    p   = doc.add_paragraph()
    pat = re.compile(r'(\*\*(.*?)\*\*|\*(.*?)\*|`(.*?)`)')
    pos = 0

    # FIX: Only strip a LONE leading/trailing backtick (broken template artifact).
    # Do NOT strip "`int` — desc" — that is valid inline code handled by pat.
    # e.g. "` — Does not return" → " — Does not return"  (lone backtick → strip)
    # e.g. "`int` — desc" → kept intact, pat renders `int` as Courier New
    if text.startswith('`') and not re.match(r'^`[^`]+`', text):
        text = text[1:].strip()
    # Strip lone trailing backtick "someText`" → "someText"
    if text.endswith('`') and not re.search(r'`[^`]+`$', text):
        text = text[:-1].strip()

    for m in pat.finditer(text):
        s, e = m.span()
        if s > pos:
            p.add_run(text[pos:s])
        if m.group(2) is not None:
            r = p.add_run(m.group(2))
            r.bold = True
        elif m.group(3) is not None:
            r = p.add_run(m.group(3))
            r.italic = True
        elif m.group(4) is not None:
            r = p.add_run(m.group(4))
            r.font.name = "Courier New"
            r.font.size = Pt(9.5)
            r.font.color.rgb = RGBColor(0x2A, 0x2A, 0x7A)
        pos = e

    if pos < len(text):
        p.add_run(text[pos:])

    return p


def _strip_inline_md(text: str) -> str:
    """Strip bold/italic/code markers for use in headings."""
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*',     r'\1', text)
    text = re.sub(r'`(.*?)`',       r'\1', text)
    return text.strip()


def _add_bottom_border(p):
    """Add a thin bottom border to a paragraph (horizontal rule effect)."""
    pPr  = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"),   "single")
    bottom.set(qn("w:sz"),    "4")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "888899")
    pBdr.append(bottom)
    pPr.append(pBdr)


# ─────────────────────────────────────────────────────────────────────────────
#  Table builder with explicit XML borders (fixes P7 table borders)
# ─────────────────────────────────────────────────────────────────────────────

def _add_table(doc: Document, table_lines: list):
    """
    Build a Word table from markdown pipe rows.
    P7: Explicit XML cell borders — not relying on 'Table Grid' style.
    """
    # Filter out separator rows (|---|---|)
    rows = [
        l for l in table_lines
        if not re.match(r'^\|[-\s|:]+\|$', l)
    ]
    if not rows:
        return

    # Parse rows into cells
    parsed = []
    for row in rows:
        cells = [c.strip() for c in row.strip("|").split("|")]
        parsed.append(cells)

    if not parsed:
        return

    max_cols = max(len(r) for r in parsed)
    table    = doc.add_table(rows=len(parsed), cols=max_cols)
    table.style = "Table Grid"

    for ri, row_data in enumerate(parsed):
        row = table.rows[ri]
        for ci in range(max_cols):
            cell = row.cells[ci]
            text = row_data[ci] if ci < len(row_data) else ""
            # Strip inline markdown from cell text
            text = _strip_inline_md(text)
            cell.text = text

            # Style header row
            if ri == 0:
                for run in cell.paragraphs[0].runs:
                    run.bold = True
                    run.font.color.rgb = RGBColor(0x22, 0x22, 0x55)
                # Header cell shading
                tc   = cell._tc
                tcPr = tc.get_or_add_tcPr()
                shd  = OxmlElement("w:shd")
                shd.set(qn("w:val"),   "clear")
                shd.set(qn("w:color"), "auto")
                shd.set(qn("w:fill"),  "E8E8F4")
                tcPr.append(shd)

            # P7: Explicit cell borders
            _set_cell_border(cell)

    doc.add_paragraph()   # spacing after table


def _set_cell_border(cell):
    """Set explicit visible borders on a table cell."""
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcBorders = OxmlElement("w:tcBorders")
    for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
        border = OxmlElement(f"w:{side}")
        border.set(qn("w:val"),   "single")
        border.set(qn("w:sz"),    "4")
        border.set(qn("w:color"), "9999BB")
        border.set(qn("w:space"), "0")
        tcBorders.append(border)
    tcPr.append(tcBorders)


# ─────────────────────────────────────────────────────────────────────────────
#  Complexity table
# ─────────────────────────────────────────────────────────────────────────────

def add_complexity_table(doc: Document, complexities: list):
    if not complexities:
        return
    doc.add_heading("📊 Complexity Analysis", level=2)
    table = doc.add_table(rows=1, cols=6)   # added Params column
    table.style = "Table Grid"

    hdr = table.rows[0].cells
    for i, h in enumerate(["Function", "Score", "Level", "Lines", "Params", "Recursive"]):
        hdr[i].text = h
        for run in hdr[i].paragraphs[0].runs:
            run.bold = True
            run.font.color.rgb = RGBColor(0x22, 0x22, 0x55)
        # Header shading
        tc   = hdr[i]._tc
        tcPr = tc.get_or_add_tcPr()
        shd  = OxmlElement("w:shd")
        shd.set(qn("w:val"),   "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"),  "E8E8F4")
        tcPr.append(shd)
        _set_cell_border(hdr[i])

    for c in complexities:
        row = table.add_row().cells
        row[0].text = c.name
        row[1].text = str(c.score)
        row[2].text = c.level
        row[3].text = str(c.lines)
        row[4].text = str(c.params) if hasattr(c, "params") else "—"
        row[5].text = "Yes" if c.has_recursion else "No"

        # Colour row by complexity level — match emoji prefix from complexity.py
        level_lower = c.level.lower()
        if "low" in level_lower:
            fill = "E2EFDA"   # green
        elif "medium" in level_lower:
            fill = "FFF2CC"   # amber
        else:
            fill = "FFE0E0"   # red

        for cell in row:
            _set_cell_border(cell)
            tc   = cell._tc
            tcPr = tc.get_or_add_tcPr()
            shd  = OxmlElement("w:shd")
            shd.set(qn("w:val"),   "clear")
            shd.set(qn("w:color"), "auto")
            shd.set(qn("w:fill"),  fill)
            tcPr.append(shd)

    doc.add_paragraph()   # spacing after table


# ─────────────────────────────────────────────────────────────────────────────
#  Architecture diagram — P5: try/except + text fallback
# ─────────────────────────────────────────────────────────────────────────────

def add_architecture(doc: Document, img_path: str, file_analyses: dict = None):
    """
    P5: Add architecture diagram. If image unavailable, insert text dependency table.
    file_analyses: optional dict of {filename: {imports, classes, functions}}
    for building the fallback text table.
    """
    doc.add_page_break()
    doc.add_heading("🏗️ Architecture Diagram", level=1)

    try:
        if img_path and __import__("os").path.exists(img_path):
            doc.add_picture(img_path, width=Inches(6))
            p = doc.add_paragraph()
            p.add_run("Figure: Cross-file dependency and call graph.").italic = True
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            return
    except Exception as e:
        print(f"    ⚠ Diagram image failed: {e} — adding text fallback")

    # P5: Text fallback — dependency table
    doc.add_paragraph(
        "Architecture diagram could not be rendered. "
        "Dependency summary below:"
    ).italic = True

    if file_analyses:
        table = doc.add_table(rows=1, cols=3)
        table.style = "Table Grid"
        hdr = table.rows[0].cells
        for i, h in enumerate(["File", "Imports", "Functions"]):
            hdr[i].text = h
            for run in hdr[i].paragraphs[0].runs:
                run.bold = True
            _set_cell_border(hdr[i])

        for fname, info in file_analyses.items():
            row = table.add_row().cells
            row[0].text = fname
            row[1].text = ", ".join(sorted(info.get("imports", [])))[:80]
            row[2].text = ", ".join(
                f.get("name", "") for f in info.get("functions", [])
            )[:80]
            for cell in row:
                _set_cell_border(cell)
    else:
        doc.add_paragraph("No dependency data available.")


# ─────────────────────────────────────────────────────────────────────────────
#  Project summary — P6: passed through _add_markdown, not raw dump
# ─────────────────────────────────────────────────────────────────────────────

def add_summary(doc: Document, summary: str):
    """
    P6: Add project summary section. Routes through _add_markdown() so that
    ### headings, **bold**, and * bullets are rendered properly in Word,
    not printed as raw markdown symbols.
    """
    doc.add_page_break()
    doc.add_heading("📋 Project Summary", level=1)
    # P6 FIX: was doc.add_paragraph(summary) — now goes through renderer
    _add_markdown(doc, summary)


# ─────────────────────────────────────────────────────────────────────────────
#  Save
# ─────────────────────────────────────────────────────────────────────────────

def save_doc(doc: Document, path: str) -> bool:
    for i in range(3):
        try:
            doc.save(path)
            print(f"  ✅ Saved: {path}")
            return True
        except PermissionError:
            print(f"  File busy, retry {i+1}/3...")
            time.sleep(2)
    return False